#!/bin/sh
# /etc/init.d/tightvncserver
### BEGIN INIT INFO
# Provides:          tightvncserver
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: tightvncserver
# Description:       tightvncserver autostart
### END INIT INFO
# Set the VNCUSER variable to the name of the user to start tightvncserver under
VNCUSER='pi'
case "$1" in
  start)
    su $VNCUSER - '/usr/bin/tightvncserver :1'
    echo "Starting TightVNC server for $VNCUSER"
    ;;
  stop)
    pkill Xtightvnc
    echo "Tightvncserver stopped:
    ;;
  *)
    echo "Usage:  /etc/init.d/tightvncserver {start|stop}"
    exit 1
    ;;
esac
exit 0
